# Generated by Django 4.2.16 on 2024-09-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='word',
            name='created_by',
        ),
    ]
