# Generated by Django 4.2.16 on 2024-09-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.CharField(max_length=100),
        ),
    ]
